package net.dawson.adorablehamsterpets.fabric.datagen;
import net.minecraft.data.recipes.RecipeOutput;
import net.minecraft.data.recipes.ShapedRecipeBuilder;
import net.minecraft.data.recipes.ShapelessRecipeBuilder;
import net.minecraft.data.recipes.SimpleCookingRecipeBuilder;

import net.dawson.adorablehamsterpets.AdorableHamsterPets;
import net.dawson.adorablehamsterpets.block.ModBlocks;
import net.dawson.adorablehamsterpets.block.custom.WoodVariant;
import net.dawson.adorablehamsterpets.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricRecipeProvider;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.data.recipes.RecipeCategory;
import net.minecraft.core.HolderLookup;
import net.minecraft.resources.Identifier;

import java.util.List;
import java.util.concurrent.CompletableFuture;

import net.minecraft.data.recipes.RecipeProvider;
import net.minecraft.data.recipes.SmithingTransformRecipeBuilder;
import net.minecraft.world.item.crafting.CookingBookCategory;

public class ModRecipeProvider extends FabricRecipeProvider {

    public ModRecipeProvider(FabricPackOutput output, CompletableFuture<HolderLookup.Provider> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected RecipeProvider createRecipeProvider(HolderLookup.Provider registries, RecipeOutput output) {
        return new Generator(registries, output);
    }

    @Override
    public String getName() {
        return "Adorable Hamster Pets Recipes";
    }

    /** Since 1.21.2 recipes are generated by a RecipeProvider instance created per run. */
    private static class Generator extends RecipeProvider {
        Generator(HolderLookup.Provider registries, RecipeOutput output) {
            super(registries, output);
        }

        /**
         * Recipe keys are passed explicitly: since 1.21.2 RecipeBuilder#save(output, String) throws when the
         * name equals the default id. Names without a namespace get the mod namespace.
         */
        private static net.minecraft.resources.ResourceKey<net.minecraft.world.item.crafting.Recipe<?>> recipeKey(String name) {
            Identifier id = name.contains(":") ? Identifier.parse(name) : Identifier.fromNamespaceAndPath(AdorableHamsterPets.MOD_ID, name);
            return net.minecraft.resources.ResourceKey.create(net.minecraft.core.registries.Registries.RECIPE, id);
        }

        // --- 2. Helpers ---
        // For Hamster Bed variants
        private void offerHamsterBedRecipe(RecipeOutput exporter, Item planks, WoodVariant variant) {
            // Result is the specific item for this variant
            Item resultItem = ModItems.HAMSTER_BED_ITEMS.get(variant).get();

            shaped(RecipeCategory.DECORATIONS, resultItem)
                    .pattern(" H ")
                    .pattern("HHH")
                    .pattern("PPP")
                    .define('H', ModItems.HAMSTER_BEDDING.get())
                    .define('P', planks)
                    .group("hamster_bed")
                    .unlockedBy("has_hamster_bedding", has(ModItems.HAMSTER_BEDDING.get()))
                    .save(exporter, recipeKey(AdorableHamsterPets.MOD_ID + ":" + "hamster_bed_" + variant.getSerializedName()));
        }

        // Helper for Smithing Upgrades
        private void offerHamsterArmorUpgrade(RecipeOutput exporter, Item template, Item material, Item result) {
            SmithingTransformRecipeBuilder.smithing(
                            Ingredient.of(template),
                            tag(ModItemTagProvider.HAMSTER_ARMOR_ENCHANTABLE), // Allow any armor tier as base
                            Ingredient.of(material),
                            RecipeCategory.COMBAT,
                            result
                    )
                    .unlocks("has_acorn_armor", has(ModItems.HAMSTER_ARMOR_ACORN.get()))
                    .unlocks("has_material", has(material))
                    .save(exporter, recipeKey(getItemName(result) + "_smithing"));
        }

        // Helper for Template Duplication
        private void offerHamsterTemplateDuplication(RecipeOutput exporter, Item template, Item material) {
            shaped(RecipeCategory.MISC, template, 2)
                    .pattern("STS")
                    .pattern("SMS")
                    .pattern("SSS")
                    .define('T', template)
                    .define('M', material)
                    .define('S', ModItems.ACORN_SHARD.get())
                    .unlockedBy("has_template", has(template))
                    .save(exporter, recipeKey(AdorableHamsterPets.MOD_ID + ":" + getItemName(template) + "_duplication"));
        }

        // Helper for Acorn Flute variantsthank you
        private void offerAcornFluteRecipe(
                RecipeOutput exporter,
                Item result,
                String recipeId,
                String middlePattern,
                Item pitcherPlant,
                Item torchflower) {
            ShapedRecipeBuilder builder = shaped(RecipeCategory.MISC, result)
                    .pattern("AAA")
                    .pattern(middlePattern)
                    .pattern("AAA")
                    .define('A', ModItems.ACORN_SHARD.get())
                    .define('S', Items.STRING)
                    .group("acorn_flute")
                    .unlockedBy("has_acorn_shard", has(ModItems.ACORN_SHARD.get()));

            if (middlePattern.indexOf('P') >= 0) {
                builder.define('P', pitcherPlant);
            }
            if (middlePattern.indexOf('T') >= 0) {
                builder.define('T', torchflower);
            }

            builder.save(exporter, recipeKey(AdorableHamsterPets.MOD_ID + ":" + recipeId));
        }

        // --- 3. Public Methods ---
        @Override
        public void buildRecipes() {
            RecipeOutput recipeExporter = this.output;
            // --- Smelting Recipes ---
            // Smelting Green Beans to Steamed Green Beans
            oreSmelting(List.of(ModItems.GREEN_BEANS.get()), RecipeCategory.FOOD, CookingBookCategory.FOOD, ModItems.STEAMED_GREEN_BEANS.get(),
                    0.35f, 200, "steamed_green_beans");

            // Smoking Green Beans to Steamed Green Beans
            SimpleCookingRecipeBuilder.smoking(Ingredient.of(ModItems.GREEN_BEANS.get()), RecipeCategory.FOOD, ModItems.STEAMED_GREEN_BEANS.get(), 0.35f, 100)
                    .group("steamed_green_beans")
                    .unlockedBy("has_green_beans", has(ModItems.GREEN_BEANS.get()))
                    .save(recipeExporter, recipeKey(AdorableHamsterPets.MOD_ID + ":" + "steamed_green_beans_from_smoking_green_beans"));

            // Smelting Acorns to Charcoal
            oreSmelting(List.of(ModItems.ACORN.get()), RecipeCategory.MISC, CookingBookCategory.MISC, Items.CHARCOAL,
                    0.15f, 200, "charcoal");

            // --- Shaped Crafting Recipes ---
            // Hamster Bed
            offerHamsterBedRecipe(recipeExporter, Items.OAK_PLANKS, WoodVariant.OAK);
            offerHamsterBedRecipe(recipeExporter, Items.SPRUCE_PLANKS, WoodVariant.SPRUCE);
            offerHamsterBedRecipe(recipeExporter, Items.BIRCH_PLANKS, WoodVariant.BIRCH);
            offerHamsterBedRecipe(recipeExporter, Items.JUNGLE_PLANKS, WoodVariant.JUNGLE);
            offerHamsterBedRecipe(recipeExporter, Items.ACACIA_PLANKS, WoodVariant.ACACIA);
            offerHamsterBedRecipe(recipeExporter, Items.DARK_OAK_PLANKS, WoodVariant.DARK_OAK);
            offerHamsterBedRecipe(recipeExporter, Items.MANGROVE_PLANKS, WoodVariant.MANGROVE);
            offerHamsterBedRecipe(recipeExporter, Items.CHERRY_PLANKS, WoodVariant.CHERRY);
            offerHamsterBedRecipe(recipeExporter, Items.BAMBOO_PLANKS, WoodVariant.BAMBOO);
            offerHamsterBedRecipe(recipeExporter, Items.PALE_OAK_PLANKS, WoodVariant.PALE_OAK);

            // Hamster Food Mix
            shaped(RecipeCategory.FOOD, ModItems.HAMSTER_FOOD_MIX.get(), 4)
                    .pattern("SSS")
                    .pattern("PCP")
                    .pattern("WWW")
                    .define('S', ModItems.SUNFLOWER_SEEDS.get())
                    .define('P', Items.PUMPKIN_SEEDS)
                    .define('C', Items.CARROT)
                    .define('W', Items.WHEAT_SEEDS)
                    .unlockedBy("has_sunflower_seeds", has(ModItems.SUNFLOWER_SEEDS.get()))
                    .save(recipeExporter, recipeKey(AdorableHamsterPets.MOD_ID + ":" + "hamster_food_mix_from_ingredients"));

            // Hamster Bedding
            shapeless(RecipeCategory.MISC, ModItems.HAMSTER_BEDDING.get(), 2)
                    .requires(Items.OAK_LEAVES)
                    .requires(Items.BIRCH_LEAVES)
                    .requires(Items.DEAD_BUSH)
                    .requires(Items.PODZOL)
                    .unlockedBy("has_oak_leaves", has(Items.OAK_LEAVES))
                    .unlockedBy("has_birch_leaves", has(Items.BIRCH_LEAVES))
                    .unlockedBy("has_dead_bush", has(Items.DEAD_BUSH))
                    .unlockedBy("has_podzol", has(Items.PODZOL))
                    .save(recipeExporter);

            // Restore Blue Cheese Disc to Regular
            shaped(RecipeCategory.MISC, ModItems.MUSIC_DISC_CHEESE.get(), 1)
                    .pattern("CCC")
                    .pattern("CDC")
                    .pattern("CCC")
                    .define('C', ModItems.CHEESE.get())
                    .define('D', ModItems.MUSIC_DISC_BLUE_CHEESE.get())
                    .unlockedBy("has_blue_cheese_disc", has(ModItems.MUSIC_DISC_BLUE_CHEESE.get()))
                    .save(recipeExporter, recipeKey(AdorableHamsterPets.MOD_ID + ":" + "music_disc_cheese_from_blue_cheese"));

            // Restore Parmesan Disc to Regular
            shaped(RecipeCategory.MISC, ModItems.MUSIC_DISC_CHEESE.get(), 1)
                    .pattern("CCC")
                    .pattern("CDC")
                    .pattern("CCC")
                    .define('C', ModItems.CHEESE.get())
                    .define('D', ModItems.MUSIC_DISC_PARMESAN.get())
                    .unlockedBy("has_parmesan_disc", has(ModItems.MUSIC_DISC_PARMESAN.get()))
                    .save(recipeExporter, recipeKey(AdorableHamsterPets.MOD_ID + ":" + "music_disc_cheese_from_parmesan"));

            // --- Shapeless Crafting Recipes ---
            // Sliced Cucumber
            shapeless(RecipeCategory.FOOD, ModItems.SLICED_CUCUMBER.get(), 3)
                    .requires(ModItems.CUCUMBER.get())
                    .unlockedBy("has_cucumber", has(ModItems.CUCUMBER.get()))
                    .save(recipeExporter);

            // Cheese
            shapeless(RecipeCategory.FOOD, ModItems.CHEESE.get(), 3)
                    .requires(Items.MILK_BUCKET)
                    .unlockedBy("has_milk_bucket", has(Items.MILK_BUCKET))
                    .save(recipeExporter);

            // Modded Sunflower to Vanilla Sunflower
            shapeless(RecipeCategory.DECORATIONS, Items.SUNFLOWER, 1)
                    .requires(ModBlocks.SUNFLOWER_BLOCK.get())
                    .unlockedBy("has_modded_sunflower", has(ModBlocks.SUNFLOWER_BLOCK.get()))
                    .save(recipeExporter, recipeKey(AdorableHamsterPets.MOD_ID + ":" + "vanilla_sunflower_from_modded"));

            // --- Acorn & Armor Recipes ---

            // Acorn Shard and Hat (Stonecutting)
            stonecutterResultFromBase(RecipeCategory.MISC, ModItems.ACORN_SHARD.get(), ModItems.ACORN.get(), 2);
            stonecutterResultFromBase(RecipeCategory.MISC, ModItems.ACORN_HAT.get(), ModItems.ACORN.get(), 1);

            // Acorn Armor (Shaped)
            shaped(RecipeCategory.COMBAT, ModItems.HAMSTER_ARMOR_ACORN.get(), 1)
                    .pattern(" H ")
                    .pattern("SSS")
                    .pattern("SSS")
                    .define('H', ModItems.ACORN_HAT.get())
                    .define('S', ModItems.ACORN_SHARD.get())
                    .unlockedBy("has_acorn_hat", has(ModItems.ACORN_HAT.get()))
                    .unlockedBy("has_acorn_shard", has(ModItems.ACORN_SHARD.get()))
                    .save(recipeExporter);

            // Acorn Ring
            shaped(RecipeCategory.MISC, ModItems.ACORN_RING.get(), 2)
                    .pattern(" C ")
                    .pattern("CHC")
                    .pattern(" C ")
                    .define('C', Items.COPPER_INGOT)
                    .define('H', ModItems.ACORN_HAT.get())
                    .unlockedBy("has_acorn_hat", has(ModItems.ACORN_HAT.get()))
                    .save(recipeExporter);

            // Acorn Flute variants
            offerAcornFluteRecipe(recipeExporter, ModItems.ACORN_FLUTE_LUSH.get(), "acorn_flute_lush", "PSP",
                    Items.PITCHER_PLANT, Items.TORCHFLOWER);
            offerAcornFluteRecipe(recipeExporter, ModItems.ACORN_FLUTE_EMBER.get(), "acorn_flute_ember", "TST",
                    Items.PITCHER_PLANT, Items.TORCHFLOWER);
            offerAcornFluteRecipe(recipeExporter, ModItems.ACORN_FLUTE_HARMONY.get(), "acorn_flute_harmony", "PST",
                    Items.PITCHER_PLANT, Items.TORCHFLOWER);
            offerAcornFluteRecipe(recipeExporter, ModItems.ACORN_FLUTE_HARMONY.get(), "acorn_flute_harmony_mirrored", "TSP",
                    Items.PITCHER_PLANT, Items.TORCHFLOWER);

            // Smithing Upgrades
            offerHamsterArmorUpgrade(recipeExporter, ModItems.HAMSTER_ARMOR_TRIM_SMITHING_TEMPLATE_IRON.get(), Items.IRON_INGOT, ModItems.HAMSTER_ARMOR_IRON.get());
            offerHamsterArmorUpgrade(recipeExporter, ModItems.HAMSTER_ARMOR_TRIM_SMITHING_TEMPLATE_GOLD.get(), Items.GOLD_INGOT, ModItems.HAMSTER_ARMOR_GOLD.get());
            offerHamsterArmorUpgrade(recipeExporter, ModItems.HAMSTER_ARMOR_TRIM_SMITHING_TEMPLATE_DIAMOND.get(), Items.DIAMOND, ModItems.HAMSTER_ARMOR_DIAMOND.get());
            offerHamsterArmorUpgrade(recipeExporter, ModItems.HAMSTER_ARMOR_TRIM_SMITHING_TEMPLATE_NETHERITE.get(), Items.NETHERITE_INGOT, ModItems.HAMSTER_ARMOR_NETHERITE.get());

            // Template Duplication
            offerHamsterTemplateDuplication(recipeExporter, ModItems.HAMSTER_ARMOR_TRIM_SMITHING_TEMPLATE_IRON.get(), Items.IRON_INGOT);
            offerHamsterTemplateDuplication(recipeExporter, ModItems.HAMSTER_ARMOR_TRIM_SMITHING_TEMPLATE_GOLD.get(), Items.GOLD_INGOT);
            offerHamsterTemplateDuplication(recipeExporter, ModItems.HAMSTER_ARMOR_TRIM_SMITHING_TEMPLATE_DIAMOND.get(), Items.DIAMOND);
            offerHamsterTemplateDuplication(recipeExporter, ModItems.HAMSTER_ARMOR_TRIM_SMITHING_TEMPLATE_NETHERITE.get(), Items.NETHERITE_INGOT);

            // --- Compacting Recipes (Crates) ---
            nineBlockStorageRecipes(RecipeCategory.MISC, ModItems.ACORN.get(), RecipeCategory.BUILDING_BLOCKS, ModItems.ACORN_CRATE.get());
            nineBlockStorageRecipes(RecipeCategory.FOOD, ModItems.CUCUMBER.get(), RecipeCategory.BUILDING_BLOCKS, ModItems.CUCUMBER_CRATE.get());
            nineBlockStorageRecipes(RecipeCategory.FOOD, ModItems.GREEN_BEANS.get(), RecipeCategory.BUILDING_BLOCKS, ModItems.GREEN_BEANS_CRATE.get());
            nineBlockStorageRecipes(RecipeCategory.FOOD, ModItems.HAMSTER_FOOD_MIX.get(), RecipeCategory.BUILDING_BLOCKS, ModItems.HAMSTER_FOOD_MIX_CRATE.get());
        }
    }
}
